item {
    id: 1
    name: 'bank_name'
}

item {
    id: 2
    name: 'customer_name'
}

item {
    id: 3
    name: 'date'
}

item {
    id: 4
    name: 'amount'
}

item {
    id: 5
    name: 'account_no'
}

item {
    id: 6
    name: 'micr_code'
}